"""adding media table

Revision ID: 3edaf53ce9f7
Revises: f90efa091f93
Create Date: 2026-07-29 18:24:19.882876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3edaf53ce9f7'
down_revision: Union[str, Sequence[str], None] = 'f90efa091f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('type', sa.Enum('image', 'video', 'audio', 'document', 'other', name='mediatype'), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('dimensions', sa.String(length=50), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('altText', sa.Text(), nullable=True),
    sa.Column('linkedContentIds', sa.JSON(), nullable=False),
    sa.Column('linkedTagIds', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_assets')
    # ### end Alembic commands ###
